version: '3'
services:
  tracker:
    container_name: tracker
    image: iodsp/fastdfs
    command: tracker
    network_mode: host
    volumes:
      - /usr/local/adinf/fastdfs/tracker_data/:/var/fdfs    
  storage0:
    container_name: storage0
    image: iodsp/fastdfs
    command: storage
    network_mode: host
    environment:
      - TRACKER_SERVER=192.168.33.10:22122
    volumes: 
      - /usr/local/adinf/fastdfs/storage_data/:/var/fdfs
    depends_on:
      - tracker
